### ISSUE TITLE
Please provide a way to set `accept_global_perms=True`

### ISSUE THREAD

**Issue by TauPan** [rpkilby/django-rest-framework-guardian#1]
Hi!

I just found out that DjangoObjectPermissionsFilter is deprecated in DRF 3.9 and going to be replaced with this module (the code is identical to the one in DRF right now, as far as I can see).

For us, the preferred behaviour is that some users get global model permissions with the intended semantics that they can view (change) *all* model objects and the ones who are only allowed to view (change) certain model objects get object permissions for the specific model.

Which means we use `accept_global_perms=True` on all our views. ;)

Currently there's no abstraction for this, so I have to completely copy + paste the whole DjangoObjectPermissionsFilter class to get the intended behaviour:
```python
from rest_framework.filters import BaseFilterBackend

class GlobalObjectPermissionsFilter(BaseFilterBackend):
    """A filter backend that limits results to those where the requesting user
    has read object level permissions.

    Contrary to the assumptions in DjangoObjectPermissionsFilter we
    assume that global model permissions mean that the user can access
    *all* objects (we use accept_global_perms on all views.)

    This means we have to copy / paste DjangoObjectPermissionsFilter
    here, since there's no abstraction to provide for that case.

    """
    def __init__(self):
        assert guardian, 'Using GlobalObjectPermissionsFilter, but django-guardian is not installed'

    perm_format = '%(app_label)s.view_%(model_name)s'

    def filter_queryset(self, request, queryset, view):
        # We want to defer this import until run-time, rather than import-time.
        # See https://github.com/encode/django-rest-framework/issues/4608
        # (Also see #1624 for why we need to make this import explicitly)
        from guardian.shortcuts import get_objects_for_user

        user = request.user
        model_cls = queryset.model
        kwargs = {
            'app_label': model_cls._meta.app_label,
            'model_name': model_cls._meta.model_name
        }
        permission = self.perm_format % kwargs
        return get_objects_for_user(user, permission, queryset,
                                    accept_global_perms=True)
```

Not sure what would be the best way here, maybe a `get_objects_for_user_kwargs` class property would simplify things.

**Comment by TauPan** [comment]
Note that for this to work, the permissions class also needs to return True for has_permission in all these cases.

**Comment by rpkilby** [comment]
Hi @TauPan. What I'll probably do here is add either a method or a class attribute that can be overridden to customize the keywords arguments.

**Comment by TauPan** [comment]
Perfect! Thanks! ;)
