### ISSUE TITLE
Allow guardian permission caching for content types

### ISSUE THREAD

**Issue by radyz** [rpkilby/django-rest-framework-guardian#14]
This is a duplicate of: https://github.com/encode/django-rest-framework/issues/5896

When using guardian to filter by object permission I noticed the `DjangoObjectPermissionsFilter` class uses the shortcut function `get_objects_for_user` to get the object queryset, however in doing so, it's building the permission parameter in the form of `app_label.view_model`. When used in this manner guardian is performing a database call each time the function is called to determine the proper content type for which the permission is valid. Instead it should be using the form of `view_model` and guardian is smart to figure out where that permission belongs from the queryset parameter and under the hood uses django's contenttype manager which caches the result so further calls do not query the database.

For the time being I'm working around this issue by overriding this class and setting `perm_format = 'view_%(model_name)s' ` instead, so when passed to guardian it's in the form of 'view_model' only.

**Comment by rpkilby** [comment]
Closing per the PR.
