### ISSUE TITLE
The HTML form field of a relationship is not filtered in the Browsable API

### ISSUE THREAD

**Issue by Helveg** [rpkilby/django-rest-framework-guardian#16]
Say you have 2 models, where model A is related to model B by a `ForeignKey` and that the authenticated user is only authorized to see a subset of the objects of model B, in the browsable API that user can still select from the full list of objects of model B instead of just the subset they're allowed to see.

I suppose this has to do with the automatically generated `Field` for the relationship inside the `Serializer` of model A. So how could I add an object permission filter to that?

**Comment by rpkilby** [comment]
Hi @Helveg. This isn't necessarily guardian-specific, but more a question of how you can limit the choices for a serializer relationship field based on the currently logged-in user. You might look at some solutions [here](https://stackoverflow.com/q/15328632/1103124).

> how could I add an object permission filter to that?

The permissions filter operates on the view itself (not the serializer), so it wouldn't be applicable. 

I'm also happy to look at a PR for a related field/mixin that simplifies this use case.

**Comment by Helveg** [comment]
My project will require these filtered sets extensively. Are there any resources to get me started on a PR for my own field/mixin?

**Comment by Helveg** [comment]
Is this problem limited to the Browsable API or can all available (ergo unfiltered by permissions) relationship objects be queried from the JSON API aswell?

**Comment by rpkilby** [comment]
Serializers do not take into account view-level permissions filtering. You must define the appropriate queryset for the serializer field. In your case, the valid queryset is based on per-object permissions.
