### ISSUE TITLE
Update README: Django 2.1+ provides view permissions by default

### ISSUE THREAD

**Issue by johnthagen** [rpkilby/django-rest-framework-guardian#5]
The README says:

> For more information on adding 'view' permissions for models, see the relevant section of the django-guardian documentation, and this blogpost.

But if you view the [latest `django-guardian` docs](https://github.com/django-guardian/django-guardian/blob/devel/docs/userguide/assign.rst#prepare-permissions), you'll see a note that Django 2.1+ already includes view permissions now.

~~Note that the latest `django-guardian` docs are not published to readthedocs yet due to https://github.com/django-guardian/django-guardian/issues/618.~~ Update: the latest docs have now been published.

The README should should probably be tweaked to show how to use the normal Django view permissions, or simply show how no extra code is needed for the user.

**Comment by rpkilby** [comment]
I'm happy to accept a docs PR if someone want to write that up. Otherwise, I'll be dropping support for  Django 2.1 and below in December, and the view permissions docs will be removed then.

**Comment by johnthagen** [comment]
@rpkilby I'm planning to write up a PR, hopefully today if I can get to it.

**Comment by rpkilby** [comment]
Fixed by d9fc987d9f1053de2ac255c480f303c28b0d0e86
