### ISSUE TITLE
No source distribution provided on PyPI

### ISSUE THREAD

**Issue by johnthagen** [rpkilby/django-rest-framework-guardian#9]
@rpkilby If a user wants to cache dependencies for offline install and use source downloads, this fails for `djangorestframework-guardian`

```
$ pip download --no-binary=:all: djangorestframework-guardian
Collecting djangorestframework-guardian
  ERROR: Could not find a version that satisfies the requirement djangorestframework-guardian (from versions: none)
ERROR: No matching distribution found for djangorestframework-guardian
```

You can see that only the `.whl` is uploaded here: https://pypi.org/project/djangorestframework-guardian/0.3.0/#files

During normal installs, `pip` will default to using `.whl`, so this will not slow down the normal use case, but will enable users to pull down source distributions if they wish.

Could `.tar.gz` source archive also be added for 0.3.0 (and future versions)?

I think the command you can use to generate it is:

```bash
$ python setup.py sdist --formats=gztar
```

**Comment by rpkilby** [comment]
Can do - I just need to make sure the sdist is setup correctly (tests/readme included in the sdist, but not installed with the package).

**Comment by johnthagen** [comment]
@rpkilby Pinging about this issue to see if it can be resolved. Thanks.

**Comment by rpkilby** [comment]
Hi @johnthagen. Finally got around to this. Basically, I wanted to ensure that the sdist included the test files, but that they weren't installed to the environment when installing the package. 

sdist for v0.3.0 is up on pypi.
